import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import { TLayout } from "@/types/root.types";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer";
import "./globals.css";


// Font for web app 
const outfitFont = Outfit({
  weight: ["100" ,"200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"]
});


// Metadata for website
export const metadata: Metadata = {
  title: "ModelVerse",
  description: "Generated by create next app",
};


export default function RootLayout({children}: TLayout) {
  return (
    <html lang="en">
      <body className={outfitFont.className}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
